spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


# OpenAI API Key
openai.api-key=${OPENAI_API_KEY}

# JDoodle Credentials
jdoodle.client-id=${JDOODLE_CLIENT_ID}
jdoodle.client-secret=${JDOODLE_CLIENT_SECRET}

logging.level.org.example.backend=INFO